export const COMPETITORS = {
  jobber: {
    name: 'Jobber',
    slug: 'jobber',
    tagline: 'The cleaning-first alternative to Jobber',
    description: 'Jobber is a popular field service management platform used across many industries. Spotless is purpose-built for cleaning and service companies, with deeper features for the workflows that matter most to your business.',
    market: 'US, Canada, Global',
    focus: 'General field service management',
    pricing: 'From $49/month (Core plan)',
    limitations: [
      'Built for all field services, not cleaning-specific',
      'No purpose-built cleaning workflows or checklists',
      'Higher starting price with fewer cleaning-focused features',
      'Generic scheduling without cleaning-specific recurring job patterns',
      'No built-in review funnelling to Google',
      'Limited multi-vertical support for adjacent services',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies and adjacent service verticals',
      'Cleaning-specific scheduling with recurring job templates',
      'Built-in Google review collection and referral programs',
      'Lower starting price with a generous free plan',
      'Custom booking forms designed for cleaning service enquiries',
      'Supports 12 service verticals from one platform',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  zenmaid: {
    name: 'ZenMaid',
    slug: 'zenmaid',
    tagline: 'Everything ZenMaid does, plus 11 more verticals',
    description: 'ZenMaid is a well-known maid service scheduling tool with a strong US community. Spotless covers everything ZenMaid does while supporting 12 service verticals, embedded payments, and a full business operating system.',
    market: 'US',
    focus: 'Maid service scheduling only',
    pricing: 'From $49/month',
    limitations: [
      'Only supports maid services — no other cleaning or service verticals',
      'US-focused with limited international support',
      'No built-in payment processing',
      'No multi-vertical support for pressure washing, auto detailing, etc.',
      'Limited automation capabilities',
      'No referral program features',
    ],
    spotlessAdvantages: [
      'Supports 12 service verticals beyond maid services',
      'Built-in payment processing with auto-billing',
      'Works for UK, Ireland, and international markets',
      'Comprehensive automation workflows',
      'Built-in referral program and review collection',
      'Free plan available — ZenMaid has no free tier',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  'housecall-pro': {
    name: 'Housecall Pro',
    slug: 'housecall-pro',
    tagline: 'Cleaning-first software vs generic home services',
    description: 'Housecall Pro serves all home service businesses from plumbing to cleaning. Spotless is built specifically for cleaning companies, with purpose-built features for cleaning workflows, scheduling patterns, and client management.',
    market: 'US',
    focus: 'General home services',
    pricing: 'From $65/month (Basic plan)',
    limitations: [
      'Built for all home services — not cleaning-specific',
      'Higher starting price point',
      'US-only focus with limited international support',
      'No cleaning-specific recurring job templates',
      'No built-in review funnelling specific to cleaning',
      'Complex feature set with tools most cleaners never use',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies — every feature is relevant',
      'Significantly lower starting price with a free plan',
      'International support including UK and Ireland',
      'Cleaning-specific scheduling patterns and recurring jobs',
      'Simpler interface focused on what cleaning companies actually need',
      'Built-in referral program and Google review collection',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: true, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  launch27: {
    name: 'Launch27',
    slug: 'launch27',
    tagline: 'The modern replacement for Launch27',
    description: 'Launch27 was one of the first maid service booking platforms. Spotless is the modern full-stack alternative with scheduling, payments, staff management, automations, and support for 12 service verticals.',
    market: 'US, Canada',
    focus: 'Maid service online booking',
    pricing: 'From $59/month',
    limitations: [
      'Aging platform with limited modern features',
      'Primarily a booking tool — lacks full business management',
      'No built-in payment processing',
      'Limited automation capabilities',
      'No staff management features',
      'No referral or review features',
    ],
    spotlessAdvantages: [
      'Modern, full-stack platform covering all business operations',
      'Built-in payment processing with auto-billing',
      'Comprehensive staff management with team portals',
      'Powerful automation workflows',
      'Built-in review collection and referral programs',
      'Free plan available with upgrade path',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: false, spotless: true },
    },
  },
  gorilladesk: {
    name: 'GorillaDesk',
    slug: 'gorilladesk',
    tagline: 'Built for cleaning, not pest control',
    description: 'GorillaDesk started in pest control and expanded to other field services. Spotless is purpose-built for cleaning companies from the ground up, with deeper features for cleaning-specific workflows.',
    market: 'US',
    focus: 'Pest control and field services',
    pricing: 'From $49/month (Basic plan)',
    limitations: [
      'Originally built for pest control — cleaning is secondary',
      'Workflows optimised for pest control routes, not cleaning schedules',
      'US-only focus',
      'No purpose-built cleaning checklists or templates',
      'No built-in referral programs',
      'Limited cleaning-specific booking forms',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies from day one',
      'Cleaning-specific scheduling, checklists, and job templates',
      'Supports 12 service verticals including pest control',
      'International support for UK and Ireland',
      'Built-in referral programs and review collection',
      'Free plan available — lower barrier to entry',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: true, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  swept: {
    name: 'Swept',
    slug: 'swept',
    tagline: 'Full-stack platform vs janitorial-only tool',
    description: 'Swept focuses specifically on janitorial and commercial cleaning operations. Spotless covers residential, commercial, and 10 additional service verticals with a complete business management platform.',
    market: 'US, Canada',
    focus: 'Janitorial and commercial cleaning only',
    pricing: 'Custom pricing (contact sales)',
    limitations: [
      'Limited to janitorial and commercial cleaning',
      'No residential cleaning support',
      'No online booking forms for customer-facing scheduling',
      'Custom pricing only — no transparent pricing page',
      'No support for adjacent verticals',
      'No free plan or self-serve trial',
    ],
    spotlessAdvantages: [
      'Covers residential, commercial, and 10 additional verticals',
      'Customer-facing online booking forms',
      'Transparent pricing with a free plan',
      'Self-serve signup with instant access',
      'Built-in payment processing',
      'Referral programs and Google review collection',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  procleaneruk: {
    name: 'ProCleanerUK',
    slug: 'procleaneruk',
    tagline: 'The modern UK cleaning software alternative',
    description: 'ProCleanerUK is a UK-based cleaning software platform. Spotless offers a more modern interface, deeper feature set, multi-vertical support, and built-in payment processing.',
    market: 'UK',
    focus: 'Cleaning companies (UK only)',
    pricing: 'From £29/month',
    limitations: [
      'Limited feature depth compared to modern platforms',
      'UK-only with limited international reach',
      'Dated user interface',
      'No built-in payment processing',
      'No automation workflows',
      'No referral or review collection features',
    ],
    spotlessAdvantages: [
      'Modern, intuitive user interface built for speed',
      'Built-in payment processing with auto-billing',
      'Powerful automation workflows',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals beyond cleaning',
      'Free plan available for new businesses',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  servicem8: {
    name: 'ServiceM8',
    slug: 'servicem8',
    tagline: 'Purpose-built cleaning software vs generic FSM',
    description: 'ServiceM8 is a field service management app originally from Australia, used across trades and services. Spotless is purpose-built for cleaning companies with cleaning-specific features and workflows.',
    market: 'Australia, UK, Global',
    focus: 'General field service management',
    pricing: 'From €29/month (Starter plan)',
    limitations: [
      'Built for general field services — not cleaning-specific',
      'Originally designed for Australian market',
      'No cleaning-specific booking forms or checklists',
      'No built-in referral programs',
      'No Google review collection',
      'Limited recurring job scheduling for cleaning patterns',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies',
      'Cleaning-specific booking forms and job templates',
      'Built-in referral programs and Google review collection',
      'Designed for cleaning-specific recurring schedules',
      'Supports 12 service verticals',
      'Free plan available',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  workiz: {
    name: 'Workiz',
    slug: 'workiz',
    tagline: 'Purpose-built cleaning platform vs generic FSM',
    description: 'Workiz is a general field service management platform from the US used across many trades and service industries. Spotless is built specifically for cleaning companies, with purpose-built workflows, checklists, and booking forms tailored to cleaning businesses.',
    market: 'US',
    focus: 'General field service management',
    pricing: 'From $65/month',
    limitations: [
      'Built for general field services — lacks cleaning-specific features',
      'Higher starting price with no free plan',
      'No cleaning-specific checklists or job templates',
      'Generic booking forms not optimised for cleaning enquiries',
      'No built-in referral program for cleaning clients',
      'Limited recurring scheduling patterns for cleaning businesses',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies with tailored workflows',
      'Cleaning-specific checklists and job templates included',
      'Lower starting price with a generous free plan',
      'Custom booking forms designed for cleaning service enquiries',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals from one platform',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  connecteam: {
    name: 'Connecteam',
    slug: 'connecteam',
    tagline: 'All-in-one cleaning software vs team management app',
    description: 'Connecteam is a workforce management app from Israel designed for deskless teams across all industries. Spotless is a complete cleaning business platform with scheduling, invoicing, payments, and customer management — not just team communication.',
    market: 'Israel, Global',
    focus: 'Workforce management app',
    pricing: 'From €29/user/month',
    limitations: [
      'Primarily a team management tool, not a cleaning business platform',
      'Per-user pricing gets expensive as your team grows',
      'No cleaning-specific scheduling or job templates',
      'No online booking forms for customers',
      'No built-in invoicing or payment processing',
      'No referral program or review collection features',
    ],
    spotlessAdvantages: [
      'Complete cleaning business platform — not just team management',
      'Flat pricing that scales affordably as you grow',
      'Built-in invoicing, payments, and auto-billing',
      'Customer-facing online booking forms',
      'Cleaning-specific scheduling with recurring job templates',
      'Built-in referral programs and Google review collection',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: false, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: true, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  fieldpulse: {
    name: 'FieldPulse',
    slug: 'fieldpulse',
    tagline: 'Cleaning-first platform vs general contractor software',
    description: 'FieldPulse is a US-based contractor management platform designed for HVAC, plumbing, and electrical businesses. Spotless is purpose-built for cleaning companies with cleaning-specific features, workflows, and booking forms.',
    market: 'US',
    focus: 'Contractor management',
    pricing: 'From $60/month',
    limitations: [
      'Built for contractors, not cleaning companies',
      'Workflows optimised for project-based trades, not recurring cleans',
      'No cleaning-specific checklists or templates',
      'No built-in referral program',
      'No Google review collection features',
      'Higher price point with no free plan',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies from the ground up',
      'Cleaning-specific recurring scheduling and job templates',
      'Built-in referral programs and Google review collection',
      'Custom booking forms for cleaning service enquiries',
      'Lower starting price with a generous free plan',
      'Supports 12 service verticals beyond cleaning',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  cleanetto: {
    name: 'Cleanetto',
    slug: 'cleanetto',
    tagline: 'Full-stack alternative to Cleanetto',
    description: 'Cleanetto is a cleaning-focused CRM from the EU that helps manage customer relationships and bookings. Spotless goes beyond CRM with full business management including payments, staff scheduling, automations, and multi-vertical support.',
    market: 'EU',
    focus: 'Cleaning-focused CRM',
    pricing: 'From €39/month',
    limitations: [
      'Limited to CRM — lacks full business management features',
      'No built-in payment processing or invoicing automation',
      'No staff scheduling or team management',
      'No automation workflows beyond basic reminders',
      'No referral program or review collection',
      'No multi-vertical support for adjacent services',
    ],
    spotlessAdvantages: [
      'Full-stack business platform beyond just CRM',
      'Built-in payment processing with auto-billing',
      'Comprehensive staff scheduling and team management',
      'Powerful automation workflows for every part of your business',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals from one platform',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: false, spotless: true },
    },
  },
  bookingkoala: {
    name: 'BookingKoala',
    slug: 'bookingkoala',
    tagline: 'Modern replacement for BookingKoala',
    description: 'BookingKoala is an online booking platform for service businesses that focuses on customer-facing booking flows. Spotless is a complete cleaning business OS with scheduling, payments, staff management, and automations beyond just booking.',
    market: 'US, Global',
    focus: 'Online booking platform for services',
    pricing: 'From $27/month',
    limitations: [
      'Primarily booking-focused — lacks full operational features',
      'No built-in staff scheduling or team management',
      'Limited automation capabilities',
      'No Google review collection or referral programs',
      'No cleaning-specific checklists or job templates',
      'Basic invoicing without integrated payment processing',
    ],
    spotlessAdvantages: [
      'Complete business OS beyond just online booking',
      'Built-in staff scheduling and team management',
      'Powerful automation workflows for follow-ups and reminders',
      'Built-in referral programs and Google review collection',
      'Cleaning-specific checklists and job templates',
      'Integrated payment processing with auto-billing',
    ],
    features: {
      scheduling: { competitor: false, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: true, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: false, spotless: true },
    },
  },
  maidcentral: {
    name: 'MaidCentral',
    slug: 'maidcentral',
    tagline: 'The all-in-one alternative to MaidCentral',
    description: 'MaidCentral is a maid service software platform from the US built specifically for maid services. Spotless covers everything MaidCentral does at a fraction of the price while supporting 12 service verticals and built-in payment processing.',
    market: 'US',
    focus: 'Maid service software',
    pricing: 'From $149/month',
    limitations: [
      'Expensive starting price at $149/month',
      'Limited to maid services only — no other cleaning verticals',
      'No multi-vertical support for adjacent services',
      'No free plan or low-cost entry tier',
      'US-only with limited international support',
      'No built-in Google review collection',
    ],
    spotlessAdvantages: [
      'Significantly lower price point with a generous free plan',
      'Supports 12 service verticals beyond maid services',
      'International support including UK and Ireland',
      'Built-in Google review collection and referral programs',
      'Built-in payment processing with auto-billing',
      'Modern interface with faster onboarding',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  tradify: {
    name: 'Tradify',
    slug: 'tradify',
    tagline: 'Built for cleaning, not trades',
    description: 'Tradify is a trades management platform from New Zealand used by electricians, plumbers, and builders. Spotless is purpose-built for cleaning companies with cleaning-specific workflows, booking forms, and recurring scheduling patterns.',
    market: 'NZ, Australia, UK',
    focus: 'Trades management',
    pricing: 'From $35/user/month',
    limitations: [
      'Designed for trades like plumbing and electrical — not cleaning',
      'Per-user pricing gets expensive as your team grows',
      'No cleaning-specific checklists or job templates',
      'No online booking forms for cleaning customers',
      'No referral program or review collection features',
      'Workflows optimised for quoting and project work, not recurring cleans',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies with tailored workflows',
      'Flat pricing that scales affordably',
      'Cleaning-specific checklists and recurring job templates',
      'Customer-facing online booking forms',
      'Built-in referral programs and Google review collection',
      'Free plan available for new businesses',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  commusoft: {
    name: 'Commusoft',
    slug: 'commusoft',
    tagline: 'Purpose-built for cleaning vs generic field service',
    description: 'Commusoft is a UK-based field service management platform built for trades and service companies. Spotless is purpose-built for cleaning businesses with cleaning-specific features, transparent pricing, and a free plan to get started.',
    market: 'UK, US',
    focus: 'Field service management',
    pricing: 'Custom pricing (contact sales)',
    limitations: [
      'General FSM — not cleaning-specific',
      'Custom pricing only — no transparent pricing page',
      'No cleaning-specific checklists or booking forms',
      'No free plan or self-serve trial',
      'No built-in referral program',
      'No Google review collection features',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies from day one',
      'Transparent pricing with a generous free plan',
      'Cleaning-specific checklists and booking forms',
      'Self-serve signup with instant access',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals from one platform',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  freshlime: {
    name: 'FreshLime',
    slug: 'freshlime',
    tagline: 'Full business platform vs customer engagement tool',
    description: 'FreshLime is a customer engagement and marketing platform from the US designed to help service businesses manage their online reputation. Spotless is a complete cleaning business platform that covers scheduling, payments, staff management, and more — not just marketing.',
    market: 'US',
    focus: 'Customer engagement and marketing',
    pricing: 'Custom pricing (contact sales)',
    limitations: [
      'Only covers marketing and customer engagement — not full business ops',
      'No scheduling, invoicing, or payment processing',
      'No staff management or team coordination features',
      'Custom pricing only — no transparent pricing',
      'No cleaning-specific workflows or checklists',
      'No online booking forms for cleaning customers',
    ],
    spotlessAdvantages: [
      'Complete business platform covering all operations',
      'Built-in scheduling, invoicing, and payment processing',
      'Comprehensive staff management with team portals',
      'Transparent pricing with a generous free plan',
      'Cleaning-specific workflows, checklists, and booking forms',
      'Built-in referral programs alongside review collection',
    ],
    features: {
      scheduling: { competitor: false, spotless: true },
      invoicing: { competitor: false, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: true, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: false, spotless: true },
    },
  },
  cleanmanager: {
    name: 'CleanManager',
    slug: 'cleanmanager',
    tagline: 'Modern alternative to CleanManager',
    description: 'CleanManager is a Danish cleaning management software platform focused on commercial cleaning operations. Spotless offers a modern interface, multi-vertical support, built-in payments, and features for both residential and commercial cleaning.',
    market: 'Denmark, Nordics, EU',
    focus: 'Commercial cleaning management',
    pricing: 'Custom pricing (contact sales)',
    limitations: [
      'Dated interface with a steep learning curve',
      'Limited to commercial cleaning — no residential support',
      'Custom pricing only — no transparent pricing page',
      'No built-in payment processing',
      'No referral program or Google review collection',
      'Limited to Nordic and EU markets',
    ],
    spotlessAdvantages: [
      'Modern, intuitive interface with fast onboarding',
      'Supports both residential and commercial cleaning',
      'Transparent pricing with a generous free plan',
      'Built-in payment processing with auto-billing',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals from one platform',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  fieldvibe: {
    name: 'Fieldvibe',
    slug: 'fieldvibe',
    tagline: 'Complete cleaning OS vs simple scheduler',
    description: 'Fieldvibe is a simple scheduling app for field service workers that focuses on basic job scheduling. Spotless is a complete cleaning business operating system with invoicing, payments, CRM, automations, and much more.',
    market: 'Global',
    focus: 'Simple scheduling app',
    pricing: 'Free / From $9/month (Pro plan)',
    limitations: [
      'Very basic — lacks invoicing, payments, and CRM',
      'No online booking forms for customers',
      'No automation workflows',
      'No referral program or review collection',
      'No cleaning-specific checklists or templates',
      'No staff management or team coordination beyond basic scheduling',
    ],
    spotlessAdvantages: [
      'Complete business OS — not just a scheduler',
      'Built-in invoicing, payments, and auto-billing',
      'Customer-facing online booking forms',
      'Powerful automation workflows',
      'Built-in referral programs and Google review collection',
      'Cleaning-specific checklists and job templates',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: false, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: true, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  cleanhq: {
    name: 'CleanHQ',
    slug: 'cleanhq',
    tagline: 'Full-stack cleaning platform vs basic management',
    description: 'CleanHQ is a basic cleaning management tool that covers simple scheduling and client tracking. Spotless is a full-stack cleaning business platform with integrated payments, automations, multi-vertical support, and advanced features.',
    market: 'US, Global',
    focus: 'Basic cleaning management',
    pricing: 'From €29/month',
    limitations: [
      'Limited features — no payment processing',
      'Basic scheduling without recurring job templates',
      'No automation workflows',
      'No referral program or Google review collection',
      'No multi-vertical support for adjacent services',
      'No staff management or team portals',
    ],
    spotlessAdvantages: [
      'Full-stack platform with integrated payment processing',
      'Advanced recurring scheduling with cleaning-specific templates',
      'Powerful automation workflows for every part of your business',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals from one platform',
      'Free plan available with comprehensive features',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: false, spotless: true },
    },
  },
};

export const FEATURE_LABELS = {
  scheduling: 'Drag-and-drop scheduling',
  invoicing: 'Invoicing & billing',
  onlineBooking: 'Online booking forms',
  staffManagement: 'Staff management',
  automations: 'Workflow automations',
  reviewCollection: 'Google review collection',
  referralProgram: 'Referral program',
  freePlan: 'Free plan available',
  cleaningChecklists: 'Cleaning-specific checklists',
  multiVertical: 'Multi-vertical support (12+)',
  customerPortal: 'Customer portal',
  mobileApp: 'Mobile app / responsive',
};

export function getCompetitor(slug) {
  return COMPETITORS[slug] || null;
}

export function getAllCompetitorSlugs() {
  return Object.keys(COMPETITORS);
}

export const ALTERNATIVES = {
  'jobber-alternatives': {
    name: 'Jobber',
    slug: 'jobber-alternatives',
    title: 'Best Jobber Alternatives for Cleaning Companies (2026)',
    description: 'Looking for a Jobber alternative built specifically for cleaning companies? Compare the top Jobber alternatives with features, pricing, and reviews.',
    competitors: ['zenmaid', 'housecall-pro', 'gorilladesk', 'servicem8'],
  },
  'housecall-pro-alternatives': {
    name: 'Housecall Pro',
    slug: 'housecall-pro-alternatives',
    title: 'Best Housecall Pro Alternatives for Cleaning Companies (2026)',
    description: 'Looking for a Housecall Pro alternative that\'s built for cleaning? Compare the best alternatives with pricing, features, and cleaning-specific tools.',
    competitors: ['jobber', 'zenmaid', 'gorilladesk', 'servicem8'],
  },
  'zenmaid-alternatives': {
    name: 'ZenMaid',
    slug: 'zenmaid-alternatives',
    title: 'Best ZenMaid Alternatives for Cleaning Businesses (2026)',
    description: 'Outgrowing ZenMaid? Compare the best ZenMaid alternatives with multi-vertical support, automation, and built-in payments.',
    competitors: ['jobber', 'housecall-pro', 'maidcentral', 'bookingkoala'],
  },
  'best-cleaning-software': {
    name: 'Best Cleaning Software',
    slug: 'best-cleaning-software',
    title: 'Best Cleaning Business Software (2026) — Top 10 Compared',
    description: 'Compare the best cleaning business software in 2026. Features, pricing, pros, and cons for Spotless, Jobber, ZenMaid, Housecall Pro, and more.',
    competitors: ['jobber', 'zenmaid', 'housecall-pro', 'launch27', 'gorilladesk', 'swept', 'servicem8', 'maidcentral'],
  },
  'best-cleaning-software-uk': {
    name: 'Best Cleaning Software UK',
    slug: 'best-cleaning-software-uk',
    title: 'Best Cleaning Business Software UK (2026) — Top Picks',
    description: 'Compare the best cleaning software for UK businesses. Find UK-friendly pricing, VAT support, and features built for the British cleaning market.',
    competitors: ['procleaneruk', 'servicem8', 'commusoft', 'tradify'],
  },
  'best-cleaning-software-ireland': {
    name: 'Best Cleaning Software Ireland',
    slug: 'best-cleaning-software-ireland',
    title: 'Best Cleaning Business Software Ireland (2026)',
    description: 'Compare the best cleaning software for Irish businesses. Euro pricing, Irish tax support, and features built for the Irish cleaning market.',
    competitors: ['procleaneruk', 'servicem8', 'jobber'],
  },
};

export function getAlternative(slug) {
  return ALTERNATIVES[slug] || null;
}

export function getAllAlternativeSlugs() {
  return Object.keys(ALTERNATIVES);
}
