export const COMPETITORS = {
  jobber: {
    name: 'Jobber',
    slug: 'jobber',
    tagline: 'The cleaning-first alternative to Jobber',
    description: 'Jobber is a popular field service management platform used across many industries. Spotless is purpose-built for cleaning and service companies, with deeper features for the workflows that matter most to your business.',
    market: 'US, Canada, Global',
    focus: 'General field service management',
    pricing: 'From $49/month (Core plan)',
    limitations: [
      'Built for all field services, not cleaning-specific',
      'No purpose-built cleaning workflows or checklists',
      'Higher starting price with fewer cleaning-focused features',
      'Generic scheduling without cleaning-specific recurring job patterns',
      'No built-in review funnelling to Google',
      'Limited multi-vertical support for adjacent services',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies and adjacent service verticals',
      'Cleaning-specific scheduling with recurring job templates',
      'Built-in Google review collection and referral programs',
      'Lower starting price with a generous free plan',
      'Custom booking forms designed for cleaning service enquiries',
      'Supports 12 service verticals from one platform',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  zenmaid: {
    name: 'ZenMaid',
    slug: 'zenmaid',
    tagline: 'Everything ZenMaid does, plus 11 more verticals',
    description: 'ZenMaid is a well-known maid service scheduling tool with a strong US community. Spotless covers everything ZenMaid does while supporting 12 service verticals, embedded payments, and a full business operating system.',
    market: 'US',
    focus: 'Maid service scheduling only',
    pricing: 'From $49/month',
    limitations: [
      'Only supports maid services — no other cleaning or service verticals',
      'US-focused with limited international support',
      'No built-in payment processing',
      'No multi-vertical support for pressure washing, auto detailing, etc.',
      'Limited automation capabilities',
      'No referral program features',
    ],
    spotlessAdvantages: [
      'Supports 12 service verticals beyond maid services',
      'Built-in payment processing with auto-billing',
      'Works for UK, Ireland, and international markets',
      'Comprehensive automation workflows',
      'Built-in referral program and review collection',
      'Free plan available — ZenMaid has no free tier',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  'housecall-pro': {
    name: 'Housecall Pro',
    slug: 'housecall-pro',
    tagline: 'Cleaning-first software vs generic home services',
    description: 'Housecall Pro serves all home service businesses from plumbing to cleaning. Spotless is built specifically for cleaning companies, with purpose-built features for cleaning workflows, scheduling patterns, and client management.',
    market: 'US',
    focus: 'General home services',
    pricing: 'From $65/month (Basic plan)',
    limitations: [
      'Built for all home services — not cleaning-specific',
      'Higher starting price point',
      'US-only focus with limited international support',
      'No cleaning-specific recurring job templates',
      'No built-in review funnelling specific to cleaning',
      'Complex feature set with tools most cleaners never use',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies — every feature is relevant',
      'Significantly lower starting price with a free plan',
      'International support including UK and Ireland',
      'Cleaning-specific scheduling patterns and recurring jobs',
      'Simpler interface focused on what cleaning companies actually need',
      'Built-in referral program and Google review collection',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: true, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  launch27: {
    name: 'Launch27',
    slug: 'launch27',
    tagline: 'The modern replacement for Launch27',
    description: 'Launch27 was one of the first maid service booking platforms. Spotless is the modern full-stack alternative with scheduling, payments, staff management, automations, and support for 12 service verticals.',
    market: 'US, Canada',
    focus: 'Maid service online booking',
    pricing: 'From $59/month',
    limitations: [
      'Aging platform with limited modern features',
      'Primarily a booking tool — lacks full business management',
      'No built-in payment processing',
      'Limited automation capabilities',
      'No staff management features',
      'No referral or review features',
    ],
    spotlessAdvantages: [
      'Modern, full-stack platform covering all business operations',
      'Built-in payment processing with auto-billing',
      'Comprehensive staff management with team portals',
      'Powerful automation workflows',
      'Built-in review collection and referral programs',
      'Free plan available with upgrade path',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: false, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: false, spotless: true },
    },
  },
  gorilladesk: {
    name: 'GorillaDesk',
    slug: 'gorilladesk',
    tagline: 'Built for cleaning, not pest control',
    description: 'GorillaDesk started in pest control and expanded to other field services. Spotless is purpose-built for cleaning companies from the ground up, with deeper features for cleaning-specific workflows.',
    market: 'US',
    focus: 'Pest control and field services',
    pricing: 'From $49/month (Basic plan)',
    limitations: [
      'Originally built for pest control — cleaning is secondary',
      'Workflows optimised for pest control routes, not cleaning schedules',
      'US-only focus',
      'No purpose-built cleaning checklists or templates',
      'No built-in referral programs',
      'Limited cleaning-specific booking forms',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies from day one',
      'Cleaning-specific scheduling, checklists, and job templates',
      'Supports 12 service verticals including pest control',
      'International support for UK and Ireland',
      'Built-in referral programs and review collection',
      'Free plan available — lower barrier to entry',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: true, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  swept: {
    name: 'Swept',
    slug: 'swept',
    tagline: 'Full-stack platform vs janitorial-only tool',
    description: 'Swept focuses specifically on janitorial and commercial cleaning operations. Spotless covers residential, commercial, and 10 additional service verticals with a complete business management platform.',
    market: 'US, Canada',
    focus: 'Janitorial and commercial cleaning only',
    pricing: 'Custom pricing (contact sales)',
    limitations: [
      'Limited to janitorial and commercial cleaning',
      'No residential cleaning support',
      'No online booking forms for customer-facing scheduling',
      'Custom pricing only — no transparent pricing page',
      'No support for adjacent verticals',
      'No free plan or self-serve trial',
    ],
    spotlessAdvantages: [
      'Covers residential, commercial, and 10 additional verticals',
      'Customer-facing online booking forms',
      'Transparent pricing with a free plan',
      'Self-serve signup with instant access',
      'Built-in payment processing',
      'Referral programs and Google review collection',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: false, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  procleaneruk: {
    name: 'ProCleanerUK',
    slug: 'procleaneruk',
    tagline: 'The modern UK cleaning software alternative',
    description: 'ProCleanerUK is a UK-based cleaning software platform. Spotless offers a more modern interface, deeper feature set, multi-vertical support, and built-in payment processing.',
    market: 'UK',
    focus: 'Cleaning companies (UK only)',
    pricing: 'From £29/month',
    limitations: [
      'Limited feature depth compared to modern platforms',
      'UK-only with limited international reach',
      'Dated user interface',
      'No built-in payment processing',
      'No automation workflows',
      'No referral or review collection features',
    ],
    spotlessAdvantages: [
      'Modern, intuitive user interface built for speed',
      'Built-in payment processing with auto-billing',
      'Powerful automation workflows',
      'Built-in referral programs and Google review collection',
      'Supports 12 service verticals beyond cleaning',
      'Free plan available for new businesses',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: false, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: true, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: false, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
  servicem8: {
    name: 'ServiceM8',
    slug: 'servicem8',
    tagline: 'Purpose-built cleaning software vs generic FSM',
    description: 'ServiceM8 is a field service management app originally from Australia, used across trades and services. Spotless is purpose-built for cleaning companies with cleaning-specific features and workflows.',
    market: 'Australia, UK, Global',
    focus: 'General field service management',
    pricing: 'From $29/month (Starter plan)',
    limitations: [
      'Built for general field services — not cleaning-specific',
      'Originally designed for Australian market',
      'No cleaning-specific booking forms or checklists',
      'No built-in referral programs',
      'No Google review collection',
      'Limited recurring job scheduling for cleaning patterns',
    ],
    spotlessAdvantages: [
      'Purpose-built for cleaning companies',
      'Cleaning-specific booking forms and job templates',
      'Built-in referral programs and Google review collection',
      'Designed for cleaning-specific recurring schedules',
      'Supports 12 service verticals',
      'Free plan available',
    ],
    features: {
      scheduling: { competitor: true, spotless: true },
      invoicing: { competitor: true, spotless: true },
      onlineBooking: { competitor: true, spotless: true },
      staffManagement: { competitor: true, spotless: true },
      automations: { competitor: true, spotless: true },
      reviewCollection: { competitor: false, spotless: true },
      referralProgram: { competitor: false, spotless: true },
      freePlan: { competitor: false, spotless: true },
      cleaningChecklists: { competitor: false, spotless: true },
      multiVertical: { competitor: false, spotless: true },
      customerPortal: { competitor: true, spotless: true },
      mobileApp: { competitor: true, spotless: true },
    },
  },
};

export const FEATURE_LABELS = {
  scheduling: 'Drag-and-drop scheduling',
  invoicing: 'Invoicing & billing',
  onlineBooking: 'Online booking forms',
  staffManagement: 'Staff management',
  automations: 'Workflow automations',
  reviewCollection: 'Google review collection',
  referralProgram: 'Referral program',
  freePlan: 'Free plan available',
  cleaningChecklists: 'Cleaning-specific checklists',
  multiVertical: 'Multi-vertical support (12+)',
  customerPortal: 'Customer portal',
  mobileApp: 'Mobile app / responsive',
};

export function getCompetitor(slug) {
  return COMPETITORS[slug] || null;
}

export function getAllCompetitorSlugs() {
  return Object.keys(COMPETITORS);
}
